modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Crimix/ArmorUnlocked/issues"
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

[[mods]]
modId="armorunlocked"
version="${version}"
displayName="Armor Unlocked"
updateJSONURL="${update_url}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/armor-unlocked"
logoFile="armorunlocked-logo.png"
credits="To all my friends for putting up with me breaking the server multiple times during testing"
authors="black_dog20"
description='''Overclock my armor'''

[[dependencies.armorunlocked]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.armorunlocked]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
